### PR TITLE
adding autobulk for faster reincarnation autobuying

### PR DESCRIPTION
**Pull request by kevmert**
if you could include these, that would be cool, also i dont know where to start looking at why frozen cookies freezes cookie clicker, i know this is a thing that happens almost every update, does it have to do with not having all of the new items "known" in the prerequisites or upgrade paths?

### CODE REVIEW

**Comment by kevmert** [comment]
looks like when i forked your master it didnt copy over your new one and kept your old one, im going to try this again

**Comment by kevmert** [comment]
also you should probably change your loading script to point to you and not Lordshinjo

**Comment by kevmert** [comment]
now that i fixed that merge im going to go change the script loader

**Comment by kevmert** [comment]
now that should load to your page, all thats left now is to get this working with the latest update and i dont know where to start with that

**Comment by briansmiley** [comment]
Hopefully this worked fine; it's my first time merging a third party pull request and I'm still very much new at the whole GitHub thing.

**Comment by briansmiley** [comment]
I'm still stuck on debugging the latest update freezing thing as well; I'm looking at the Error that pops up in the JS console when you load FC and it's a little tough to see exactly what's getting called since everything is like 3 functions deep. Almost certainly seems to have something to do with some upgrade/purchase list type function being confused by the new Sugar Frenzy switch.

**Pull request merged**
